# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(794, 586)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.widget_5 = QtWidgets.QWidget(self.frame_2)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.lbl_selectconf = QtWidgets.QLabel(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_selectconf.sizePolicy().hasHeightForWidth())
        self.lbl_selectconf.setSizePolicy(sizePolicy)
        self.lbl_selectconf.setObjectName("lbl_selectconf")
        self.gridLayout_11.addWidget(self.lbl_selectconf, 0, 0, 1, 1)
        self.combobox_configurations = QtWidgets.QComboBox(self.widget_5)
        self.combobox_configurations.setMaxVisibleItems(5)
        self.combobox_configurations.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.combobox_configurations.setObjectName("combobox_configurations")
        self.gridLayout_11.addWidget(self.combobox_configurations, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.widget_5, 1, 0, 1, 2)
        self.widget_4 = QtWidgets.QWidget(self.frame_2)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.button_load = QtWidgets.QPushButton(self.widget_4)
        self.button_load.setObjectName("button_load")
        self.gridLayout_7.addWidget(self.button_load, 0, 1, 1, 1)
        self.button_save = QtWidgets.QPushButton(self.widget_4)
        self.button_save.setObjectName("button_save")
        self.gridLayout_7.addWidget(self.button_save, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.widget_4, 2, 0, 1, 2)
        self.lbl_config = QtWidgets.QLabel(self.frame_2)
        self.lbl_config.setObjectName("lbl_config")
        self.gridLayout_6.addWidget(self.lbl_config, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_2, 1, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2.addWidget(self.widget_2, 4, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.button_info = QtWidgets.QToolButton(self.frame)
        self.button_info.setStyleSheet(" border-radius:50px;\n"
" max-width:24px;\n"
" max-height:24px;\n"
" min-width:24px;\n"
" min-height:24px;\n"
" background: transparent;")
        self.button_info.setText("")
        self.button_info.setAutoRaise(True)
        self.button_info.setObjectName("button_info")
        self.gridLayout_4.addWidget(self.button_info, 0, 1, 1, 1)
        self.lbl_gamecommands = QtWidgets.QLabel(self.frame)
        self.lbl_gamecommands.setObjectName("lbl_gamecommands")
        self.gridLayout_4.addWidget(self.lbl_gamecommands, 0, 0, 1, 1)
        self.widget_7 = QtWidgets.QWidget(self.frame)
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.widget_7)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.button_start = QtWidgets.QPushButton(self.widget_7)
        self.button_start.setObjectName("button_start")
        self.gridLayout_10.addWidget(self.button_start, 1, 0, 1, 2)
        self.button_clear = QtWidgets.QPushButton(self.widget_7)
        self.button_clear.setObjectName("button_clear")
        self.gridLayout_10.addWidget(self.button_clear, 0, 0, 1, 1)
        self.button_singlestep = QtWidgets.QPushButton(self.widget_7)
        self.button_singlestep.setObjectName("button_singlestep")
        self.gridLayout_10.addWidget(self.button_singlestep, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.widget_7, 3, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.frame)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.checkbox_age = QtWidgets.QCheckBox(self.widget_3)
        self.checkbox_age.setObjectName("checkbox_age")
        self.gridLayout_8.addWidget(self.checkbox_age, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget_3, 1, 0, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.frame)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.lbl_speed = QtWidgets.QLabel(self.widget_6)
        self.lbl_speed.setObjectName("lbl_speed")
        self.gridLayout_9.addWidget(self.lbl_speed, 0, 0, 1, 1)
        self.slider_speed = QtWidgets.QSlider(self.widget_6)
        self.slider_speed.setOrientation(QtCore.Qt.Horizontal)
        self.slider_speed.setObjectName("slider_speed")
        self.gridLayout_9.addWidget(self.slider_speed, 1, 0, 1, 1)
        self.lbl_fps = QtWidgets.QLabel(self.widget_6)
        self.lbl_fps.setObjectName("lbl_fps")
        self.gridLayout_9.addWidget(self.lbl_fps, 2, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget_6, 2, 0, 1, 2)
        self.gridLayout_2.addWidget(self.frame, 3, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.widget_10 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(60)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_10.sizePolicy().hasHeightForWidth())
        self.widget_10.setSizePolicy(sizePolicy)
        self.widget_10.setObjectName("widget_10")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_10)
        self.gridLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_11 = QtWidgets.QFrame(self.widget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.lbl_time = QtWidgets.QLabel(self.frame_11)
        self.lbl_time.setObjectName("lbl_time")
        self.gridLayout_13.addWidget(self.lbl_time, 0, 0, 1, 1)
        self.lbl_population = QtWidgets.QLabel(self.frame_11)
        self.lbl_population.setObjectName("lbl_population")
        self.gridLayout_13.addWidget(self.lbl_population, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.frame_11, 1, 0, 1, 1)
        self.frame_gamegrid = QtWidgets.QFrame(self.widget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(90)
        sizePolicy.setHeightForWidth(self.frame_gamegrid.sizePolicy().hasHeightForWidth())
        self.frame_gamegrid.setSizePolicy(sizePolicy)
        self.frame_gamegrid.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_gamegrid.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_gamegrid.setObjectName("frame_gamegrid")
        self.game_frame = QtWidgets.QFormLayout(self.frame_gamegrid)
        self.game_frame.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.game_frame.setContentsMargins(0, 0, 0, 0)
        self.game_frame.setHorizontalSpacing(6)
        self.game_frame.setObjectName("game_frame")
        self.gridLayout_5.addWidget(self.frame_gamegrid, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget_10, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Conoway\'s Game of Life"))
        self.lbl_selectconf.setText(_translate("MainWindow", "Select a configuration:"))
        self.button_load.setText(_translate("MainWindow", "Load"))
        self.button_save.setText(_translate("MainWindow", "Save"))
        self.lbl_config.setText(_translate("MainWindow", "Configuration Settings"))
        self.lbl_gamecommands.setText(_translate("MainWindow", "Game Commands"))
        self.button_start.setText(_translate("MainWindow", "Start"))
        self.button_clear.setText(_translate("MainWindow", "Reset"))
        self.button_singlestep.setText(_translate("MainWindow", "Single Step"))
        self.checkbox_age.setText(_translate("MainWindow", "Show Cell Age"))
        self.lbl_speed.setText(_translate("MainWindow", "Speed:"))
        self.lbl_fps.setText(_translate("MainWindow", "FPS"))
        self.lbl_time.setText(_translate("MainWindow", "Time:"))
        self.lbl_population.setText(_translate("MainWindow", "Population:"))

